openapi: 3.0.3
info:
  title: 微服务
  version: "1.0"
servers:
- url: http://localhost:8000/starter
  description: 微服务
paths:
  /api/user/get_captcha_image:
    post:
      tags:
      - User
      summary: 获取图形验证码
      description: 获取图形验证码
      operationId: User#GetCaptchaImage
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCaptchaImageResponseBody'
              example:
                data:
                  captchaId: Aut non eos sunt consequatur.
                  image: Ullam vero quia mollitia necessitatibus velit maiores.
                errcode: 0
                errmsg: ""
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /api/user/login_by_mobile:
    post:
      tags:
      - User
      summary: 使用短信验证码登录
      description: 使用短信验证码登录
      operationId: User#LoginBySmsCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBySmsCodeRequestBody'
            example:
              mobile: guest
              verify_code: "123456"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginByUsernameResponseBody'
              example:
                data:
                  credentials:
                    expires_in: 25200
                    token: eyJhbGciOiJIUz...
                  user:
                    id: Eum fugiat nesciunt velit.
                    isActive: true
                    mobile: Voluptas quasi.
                    nickname: Officiis sunt eum et repellat itaque itaque.
                    username: Magni quia.
                errcode: 0
                errmsg: ""
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
  /api/user/login_by_username:
    post:
      tags:
      - User
      summary: 使用账号密码登录
      description: 使用账号密码登录
      operationId: User#LoginByUsername
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginByUsernameRequestBody'
            example:
              captchaId: ar5
              humanCode: apa
              password: password
              username: user
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginByUsernameResponseBody'
              example:
                data:
                  credentials:
                    expires_in: 25200
                    token: eyJhbGciOiJIUz...
                  user:
                    id: Eum fugiat nesciunt velit.
                    isActive: true
                    mobile: Voluptas quasi.
                    nickname: Officiis sunt eum et repellat itaque itaque.
                    username: Magni quia.
                errcode: 0
                errmsg: ""
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
  /api/user/send_sms_code:
    post:
      tags:
      - User
      summary: 发送短信验证码
      description: 发送短信验证码
      operationId: User#SendSmsCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendSmsCodeRequestBody'
            example:
              captchaId: h
              humanCode: w5e
              mobile: nqo
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePasswordResponseBody'
              example:
                data:
                  ok: true
                errcode: 0
                errmsg: ""
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
  /api/user/update_password:
    post:
      tags:
      - User
      summary: 修改登录密码
      description: 修改登录密码
      operationId: User#UpdatePassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePasswordRequestBody'
            example:
              new_password: abc123
              old_password: 123abc
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdatePasswordResponseBody'
              example:
                data:
                  ok: true
                errcode: 0
                errmsg: ""
        "400":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
        "500":
          description: ""
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
      security:
      - jwt_header_Authorization:
        - role:user
        - role:admin
components:
  schemas:
    Captcha:
      type: object
      properties:
        captchaId:
          type: string
          description: 验证码ID
          example: Et aut a praesentium tenetur explicabo maiores.
        image:
          type: string
          description: 图片base64
          example: Et labore doloribus impedit cupiditate hic.
      example:
        captchaId: Ullam impedit repellendus eveniet sed aliquid enim.
        image: Numquam ex quasi dolores distinctio voluptate ea.
      required:
      - image
      - captchaId
    Credentials:
      type: object
      properties:
        expires_in:
          type: integer
          description: 有效时长（秒）：生成之后x秒内有效
          example: 25200
          format: int64
        token:
          type: string
          description: JWT token
          example: eyJhbGciOiJIUz...
      example:
        expires_in: 25200
        token: eyJhbGciOiJIUz...
      required:
      - token
      - expires_in
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        fault: true
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GetCaptchaImageResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Captcha'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          captchaId: Aut non eos sunt consequatur.
          image: Ullam vero quia mollitia necessitatibus velit maiores.
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    LoginBySmsCodeRequestBody:
      type: object
      properties:
        mobile:
          type: string
          description: 手机号
          example: guest
          minLength: 11
          maxLength: 11
        verify_code:
          type: string
          description: 短信验证码
          example: "123456"
          minLength: 4
          maxLength: 6
      example:
        mobile: guest
        verify_code: "123456"
      required:
      - mobile
      - verify_code
    LoginByUsernameRequestBody:
      type: object
      properties:
        captchaId:
          type: string
          description: 图形验证码ID
          default: ""
          example: w5m
          minLength: 1
          maxLength: 128
        humanCode:
          type: string
          description: 图形验证码
          default: ""
          example: "541"
          minLength: 4
          maxLength: 8
        password:
          type: string
          description: 密码
          example: password
          minLength: 1
          maxLength: 128
        username:
          type: string
          description: 用户名
          example: user
          minLength: 1
          maxLength: 128
      example:
        captchaId: e5
        humanCode: lvj
        password: password
        username: user
      required:
      - username
      - password
    LoginByUsernameResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Session'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          credentials:
            expires_in: 25200
            token: eyJhbGciOiJIUz...
          user:
            id: Eum fugiat nesciunt velit.
            isActive: true
            mobile: Voluptas quasi.
            nickname: Officiis sunt eum et repellat itaque itaque.
            username: Magni quia.
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    SendSmsCodeRequestBody:
      type: object
      properties:
        captchaId:
          type: string
          description: 图形验证码ID
          example: r93
          minLength: 1
          maxLength: 128
        humanCode:
          type: string
          description: 图形验证码
          example: ruu
          minLength: 4
          maxLength: 8
        mobile:
          type: string
          description: 手机号
          example: wnc
          minLength: 11
          maxLength: 11
      example:
        captchaId: 4ee
        humanCode: 0a3
        mobile: yhb
      required:
      - mobile
      - humanCode
      - captchaId
    Session:
      type: object
      properties:
        credentials:
          $ref: '#/components/schemas/Credentials'
        user:
          $ref: '#/components/schemas/User'
      description: 会话
      example:
        credentials:
          expires_in: 25200
          token: eyJhbGciOiJIUz...
        user:
          id: Eum fugiat nesciunt velit.
          isActive: true
          mobile: Voluptas quasi.
          nickname: Officiis sunt eum et repellat itaque itaque.
          username: Magni quia.
      required:
      - user
      - credentials
    Successresult:
      type: object
      properties:
        ok:
          type: boolean
          description: success
          example: true
      description: 成功信息
      example:
        ok: true
      required:
      - ok
    UpdatePasswordRequestBody:
      type: object
      properties:
        new_password:
          type: string
          example: abc123
          minLength: 6
          maxLength: 128
        old_password:
          type: string
          example: 123abc
          minLength: 1
          maxLength: 128
      example:
        new_password: abc123
        old_password: 123abc
      required:
      - old_password
      - new_password
    UpdatePasswordResponseBody:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Successresult'
        errcode:
          type: integer
          description: 错误码
          example: 0
          minimum: 0
          maximum: 999999
        errmsg:
          type: string
          description: 错误消息
          example: ""
      example:
        data:
          ok: true
        errcode: 0
        errmsg: ""
      required:
      - errcode
      - errmsg
    User:
      type: object
      properties:
        id:
          type: string
          description: ID
          example: Vero quisquam corporis nemo sit.
        isActive:
          type: boolean
          description: 是否可用
          example: true
        mobile:
          type: string
          description: 手机号
          example: Quia ullam earum consequatur.
        nickname:
          type: string
          description: 昵称
          example: Aperiam soluta molestiae tenetur.
        username:
          type: string
          description: 用户名
          example: Atque hic.
      description: 用户
      example:
        id: Velit dolorem.
        isActive: true
        mobile: Et ducimus culpa hic officia dolore quia.
        nickname: Eius pariatur fuga iste adipisci iure.
        username: Et rerum reiciendis aut voluptas ut.
      required:
      - id
      - username
      - nickname
      - mobile
      - isActive
  securitySchemes:
    jwt_header_Authorization:
      type: http
      description: JWT 认证
      scheme: bearer
